"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LAZY_MARK_KEY_LIST = exports.EnumLazyMarkKeys = void 0;
var EnumLazyMarkKeys;
(function (EnumLazyMarkKeys) {
    EnumLazyMarkKeys["_0"] = "0";
    EnumLazyMarkKeys["_1"] = "1";
    EnumLazyMarkKeys["_2"] = "2";
    EnumLazyMarkKeys["_3"] = "3";
    EnumLazyMarkKeys["_4"] = "4";
    EnumLazyMarkKeys["_5"] = "5";
    EnumLazyMarkKeys["_7"] = "7";
    EnumLazyMarkKeys["_8"] = "8";
    EnumLazyMarkKeys["_33"] = "33";
    EnumLazyMarkKeys["CLEAR_001"] = "clear_001";
    EnumLazyMarkKeys["CLEAR_002"] = "clear_002";
    EnumLazyMarkKeys["REPLACE_001"] = "replace_001";
    EnumLazyMarkKeys["LN_TALK"] = "ln_talk";
    EnumLazyMarkKeys["LN"] = "ln";
    EnumLazyMarkKeys["LN_0010"] = "ln_0010";
    EnumLazyMarkKeys["LN_0020"] = "ln_0020";
    EnumLazyMarkKeys["LTRIM"] = "ltrim";
    EnumLazyMarkKeys["EN"] = "en";
    EnumLazyMarkKeys["EN2"] = "en2";
    EnumLazyMarkKeys["ZH"] = "zh";
    EnumLazyMarkKeys["ZH_CHT"] = "zh_cht";
    EnumLazyMarkKeys["ZH2"] = "zh2";
    EnumLazyMarkKeys["JP1"] = "jp1";
    EnumLazyMarkKeys["CLASS"] = "class";
    EnumLazyMarkKeys["CLASS_002"] = "class_002";
    EnumLazyMarkKeys["C000"] = "c000";
    EnumLazyMarkKeys["C050"] = "c050";
    EnumLazyMarkKeys["C100"] = "c100";
    EnumLazyMarkKeys["UNIT"] = "unit";
    EnumLazyMarkKeys["FULL_WIDTH_001"] = "full_width_001";
    EnumLazyMarkKeys["FULL_WIDTH_002"] = "full_width_002";
})(EnumLazyMarkKeys = exports.EnumLazyMarkKeys || (exports.EnumLazyMarkKeys = {}));
exports.LAZY_MARK_KEY_LIST = ["0" /* _0 */, "1" /* _1 */, "2" /* _2 */, "3" /* _3 */, "4" /* _4 */, "5" /* _5 */, "7" /* _7 */, "8" /* _8 */, "33" /* _33 */, "clear_001" /* CLEAR_001 */, "clear_002" /* CLEAR_002 */, "replace_001" /* REPLACE_001 */, "ln_talk" /* LN_TALK */, "ln" /* LN */, "ln_0010" /* LN_0010 */, "ln_0020" /* LN_0020 */, "ltrim" /* LTRIM */, "en" /* EN */, "en2" /* EN2 */, "zh" /* ZH */, "zh_cht" /* ZH_CHT */, "zh2" /* ZH2 */, "jp1" /* JP1 */, "class" /* CLASS */, "class_002" /* CLASS_002 */, "c000" /* C000 */, "c050" /* C050 */, "c100" /* C100 */, "unit" /* UNIT */, "full_width_001" /* FULL_WIDTH_001 */, "full_width_002" /* FULL_WIDTH_002 */];
//# sourceMappingURL=pattern-keys.js.map